### ISSUE TITLE
[BUG] I have no girlfriend!

### ISSUE THREAD

**Issue by hzhangxyz** [god/man#25]
I have no girlfriend, this is really a very critical bug. pls fix it.

**Comment by god** [comment]
A few resources:

https://tinder.com
https://www.dmarge.com/2015/08/chris-hemsworth-style.html
https://www.wikihow.com/Become-a-Monk

**Comment by pengMaster** [comment]
so nb

**Comment by hzhangxyz** [comment]
this bug fixed now thx
