### ISSUE TITLE
COVID-19

### ISSUE THREAD

**Issue by Almo7aya** [god/man#32]
Chinese found a vulnerability in the human's body and they really abused it, They spread a very dangerous virus that infects more than 300k, the life in Earth is almost stopped and we all know that You don't want that to happen, so please fix that bug ASAP or it will kill us all.

**Comment by MitchTalmadge** [comment]
This is a serious bug, is a fix being worked on?

**Comment by god** [comment]
FIX: Do not eat the rats with the wings on them.
