### ISSUE TITLE
[Critical Bug] Cannot get a girlfriend [woman] 

### ISSUE THREAD

**Issue by Panchajanya1999** [god/man#43]
Should be considered as a bug. Not everyone is affected by it. 
@god should be blamed for not providing a good face and some more moneys. 
Anyway, this is a bug and needs a fix.

**Comment by sohamxda7** [comment]
maybe backporting some stuff from god may help. what do you think?

**Comment by Panchajanya1999** [comment]
> maybe backporting some stuff from god may help. what do you think?

Possibly, who knows? But God have few proprietary stuffs.

**Comment by Dyneteve** [comment]
> > maybe backporting some stuff from god may help. what do you think?
> 
> Possibly, who knows? But God have few proprietary stuffs.

This bug can be fixed by being gay. If this answers was helpful don't forget to close the issue ask god's angel again for any question.
With regards,
Dyneteve

**Comment by lakgarg** [comment]
Get a log atleast.

**Comment by Panchajanya1999** [comment]
> > > maybe backporting some stuff from god may help. what do you think?
> > 
> > 
> > Possibly, who knows? But God have few proprietary stuffs.
> 
> This bug can be fixed by being gay. If this answers was helpful don't forget to close the issue ask god's angel again for any question.
> With regards,
> Dyneteve

Follow the rules. Do not go for any holes around. 
Let @god decide!!

**Comment by Panchajanya1999** [comment]
> Get a log atleast.

U need su for dmesg. It is not available at this moment. pstore is un-accessible till you are alive. Maybe appoint a surgeon to get console-* after your death.

**Comment by Panchajanya1999** [comment]
I am closing this issue. Seems like God is on a vacation lately !
