### ISSUE TITLE
почему аня залупа ебаная шалава?

### ISSUE THREAD

**Issue by m4x3r1337** [god/man#48]
м??

**Comment by iNeoony** [comment]
потому что шлюха блять

**Comment by iNeoony** [comment]
ЗАКАТ ЛОХ ЕБАННЫЙ ЗПХАВЗПХАВЗПХВАЩПЗХАВЩПХЗВПЩХЗРЩХЗВШРХЗЫПШХЗАРОЩПШЩОЕЗЩАВЛДЛОЫАЛВ

**Comment by ctwoon** [comment]
@iNeoony согл

**Comment by ctwoon** [comment]
а вот с миксером не согл миксер фу

**Comment by iNeoony** [comment]
@ctwoon кто ебать

**Comment by m4x3r1337** [comment]
хочу срать сори

**Comment by clownless** [comment]
> а вот с миксером не согл миксер фу

ты лошпед
