### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bulters** [god/man#8]
Are You considering open-sourcing this? Which license?

**Comment by coffins** [comment]
I guess GOD GPL v1001

**Comment by barbier** [comment]
WTFPL? You know..... Free will and stuff....

**Comment by god** [comment]
Yes, in the name of free will (although not to be taken too seriously, else eternal damnation, etc), let's license this under WTFPL. Will update README accordingly.

**Comment by bulters** [comment]
Thank god!

**Comment by god** [comment]
You're welcome!
